---
name: Scaffold a service
on:
  workflow_dispatch:
    inputs:
      service:
        required: true
permissions:
  contents: read
env:
  AQUA_CONFIG: ${{github.workspace}}/.ci/aqua.yaml
  MAIN_REPO: gha-trigger/example-main
  SERVICE: ${{inputs.service}}
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}

      - uses: actions/checkout@v3
        with:
          repository: ${{env.MAIN_REPO}}
          token: ${{steps.generate_token.outputs.token}}
      - uses: actions/checkout@v3
        with:
          path: .ci

      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.19.2

      - run: mkdir -p "$(dirname "$SERVICE")"
      - run: cp -R template "$SERVICE"
      - run: git add "$SERVICE"
      - run: git ls-files | xargs -n 1 sed -i 's|%SERVICE%|${{env.SERVICE}}|g'
        working-directory: ${{env.SERVICE}}

      - run: |
          echo "::set-output name=branch::scaffold-${SERVICE}-$(date +%Y%m%dT%H%M%S)"
        id: branch

      - run: |
          git diff --cached --name-only "${{inputs.service}}" |
            xargs ghcp commit -r "$MAIN_REPO" \
              -b "${{steps.branch.outputs.branch}}" \
              -m "scaffold a service (${SERVICE})"
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
      - run: |
          cat << EOS >> "$GITHUB_STEP_SUMMARY"

          ## Create a scaffold pull request
          
          Please run the following command in your terminal.

          $CODE_BLOCK
          gh pr create -R "$MAIN_REPO" \\
            -H "${{steps.branch.outputs.branch}}" \\
            -t "Scaffold a service (${SERVICE})" \\
            -b "This pull request was created by [GitHub Actions](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
          $CODE_BLOCK
          EOS
        env:
          CODE_BLOCK: "```"
